name: NPM Audit Fix Run

on: {}

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@v1
    with:
      force: ${{ inputs.force || false }}
      base_branch: ${{ inputs.base_branch || 'main' }}
      node_version: "${{ inputs.node_version || '24' }}"
