name: Auto Cherry-Pick from Upstream

on:
  
  pull_request:
    types: [ labeled, opened, synchronize ]
    branches:
      - main

jobs:
  cherry-pick:
    if: github.event_name == 'workflow_dispatch' ||
      contains(fromJson(toJson(github.event.pull_request.labels)).*.name,
      'review-required')
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: "stefanzweifel"
      repo-name: "git-auto-commit-action"
      base_branch: ${{ inputs.base_branch }}
      mode: ${{ github.event_name == 'pull_request' && 'verify' || inputs.mode }}
      node_version: "${{ inputs.node_version || '24' }}"
