name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install testing dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
